#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# 
# Requirements:
# 
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
# For your answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements

# Update
apt-get -y update

# This command installs the software-properties-common package,
# which allows you to manage software repositories.
apt-get install --no-install-recommends software-properties-common

# You will get the latest release of HAProxy 2.8 (and stick to this branch).
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

# Define the HAProxy configuration
configure_haproxy() {
  sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
  sudo touch /etc/haproxy/haproxy.cfg

  local server_config="
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 531008-web-01 54.234.73.177:80 check
    server 531008-web-02 18.233.62.214:80 check
  "

  echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
}


start_haproxy() {
  sudo service haproxy start
}

verify_haproxy_status() {
  if sudo service haproxy status | grep -q "active (running)"; then
    echo "HAProxy is running."
  else
    echo "HAProxy is not running."
  fi
}
