#!/usr/bin/env bash
# the script should run the whoami command under the user passed as an argument

# Check if the script is called with one argument
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <username>"
    exit 1
fi

username="$1"

# Check if the user exists
if id "$username" &>/dev/null; then
    su - "$username" -c 'whoami'
else
    echo "User '$username' does not exist."
fi
